# Generated by Django 3.2.25 on 2024-09-27 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('episode_id', models.IntegerField()),
                ('film_id', models.IntegerField(default=None)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('length', models.FloatField()),
                ('crew', models.IntegerField()),
                ('passengers', models.IntegerField()),
                ('films', models.ManyToManyField(related_name='starship', to='starwars_api.Film')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('height', models.IntegerField()),
                ('mass', models.IntegerField()),
                ('films', models.ManyToManyField(related_name='characters', to='starwars_api.Film')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_ip', models.GenericIPAddressField()),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='starwars_api.character')),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='starwars_api.film')),
                ('starship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='starwars_api.starship')),
            ],
            options={
                'unique_together': {('character', 'film', 'starship', 'voter_ip')},
            },
        ),
    ]
