# Generated by Django 3.2.25 on 2024-09-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwars_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starship',
            name='passengers',
            field=models.CharField(blank=True, default='N/A', max_length=10),
        ),
    ]
